### PR TITLE
added logic language + style

### PR DESCRIPTION
**Pull request by JhonM**

### CODE REVIEW

**Comment by aethemba** [comment]
@JhonM  , is this supposed to go into develop, or should it go into saas?

**Comment by JhonM** [comment]
In develop initially but we can moved it to Saas.

**Comment by aethemba** [comment]
@JhonM , was this specifically done for Booking? If so, we should move it into develop, otherwise Saas would be the appropriate branch.

**Comment by JhonM** [comment]
Booking don't have multiple languages right? So it can be moved to Saas.

**Comment by aethemba** [comment]
yeah

**Pull request closed without merging**
