### PR TITLE
Hotfix/stripe account status

### PR DESCRIPTION
**Pull request by gannetson**

### CODE REVIEW

**Comment by eodolphi** [comment]
Looks good. We do not need any frontend changes for this right?

**Comment by gannetson** [comment]
Not entirely sure. I think it just worked like this, but we _are_ introducing a new status `incomplete` that the front-end doesn't handle yet. But since front-end will always ask Stripe for the details, I think this just might work (remember testing it).

**Comment by Pieter-Rees** [comment]
Can we make a test release branch for this so that Charif can test this afternoon?

**Comment by gannetson** [comment]
We can. It will overwrite the bulk transition release branch though

**Pull request merged**
