### PR TITLE
Make sure old project and tasks show in statics

### PR DESCRIPTION
**Pull request by gannetson**

### CODE REVIEW

**Comment by ashutoshb** [comment]
@gannetson : I haven't checked if the old task members are missing in the task member status log. If so, then should we also consider doing the migration for the missing task member -> task member status log in this PR itself or maybe make a new PR for it. The rest of the PR looks good.

**Comment by gannetson** [comment]
I haven't looked at TaskMembers, makes sense to do a data migration for that too. I'll look into it. 
So are you confident this migration won't mess up metrics in the sense that it will trigger events? @ashutoshb

**Comment by ashutoshb** [comment]
@gannetson : there are no influxdb entries sent on trigger events on *logs Models. 👍

**Comment by gannetson** [comment]
@ashutoshb, added task member log too

**Pull request merged**
