### PR TITLE
Refunded donations are not cancelled. They should not be counted in the

### PR DESCRIPTION
**Pull request by eodolphi**
total amount in the frontend.

BB-12990 #resolve

### CODE REVIEW

**Comment by eodolphi** [comment]
@gannetson I do not really understand why you changed the definition of amount_cancelled, but it breaks how projects show in the frontend.

Maybe we should display another property in the backoffice? For now this fixes BB-12990

**Comment by gannetson** [comment]
@eodolphi Because for (completely) refunded projects they want to show the initial amount raised. 
What would be the use of amount_cancelled?
My idea was dat the front-end would only show amount_cancelled and cancelled donations if the project status is set to 'refunded'.

**Comment by eodolphi** [comment]
Amount cancelled is exactly that. The amount that is returned to the supporters after the project failed. For these projects is seems logical to me that the amount_raised is 0, since everything is returned...

**Comment by danielkroon** [comment]
@eodolphi @gannetson I tested this on testing and it worked. Since the resolve date is today you can continue your discussing but we need this fix only today :) I discussed this with Ernst.

**Pull request merged**
