### PR TITLE
BB-8576: filter projects by country

### PR DESCRIPTION
**Pull request by ashutoshb**

### CODE REVIEW

**Comment by ashutoshb** [comment]
[Jira Comment](https://onepercentclub.atlassian.net/browse/BB-8576?focusedCommentId=39517&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-39517)

**Comment by eodolphi** [comment]
Cool. The first one!

**Comment by gannetson** [comment]
hip hip hurray! :)

**Comment by Pieter-Rees** [comment]
Congrats Ashu!

**Pull request merged**
